### ISSUE TITLE
ODS > Data Tables

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/Orange-Boosted-Bootstrap#1049]
## Requirement

**For** a Developer 
**Who** is creating an Orange Website
**The** Data Tables Integration
**is an** automated component
**that** proposes the web site's Orange Data Table components
**unlike** the default bootstrap framework
**Boosted** will provide this ready to use component compatible with the Orange Design and the accessibility requirements

## Description

Users can build a form into the website with all the following:
* Tables with Headers
* Tables with Row Selection
* Tables with Row Selection and Icons
* Tables with Row Selection and Image Thumbnails
* Tables with Icons
* Expanding Row
* Large Expanding Row
* Column Filter
* Light & Dark mode support

## References

Orange Design System: [Modules > Data Tables
](https://system.design.orange.com/0c1af118d/p/21b04a-data-tables/b/56a1a9)

## Implementation

- [X] Tables with Headers
- [X] Tables with Row Selection
- [X] Tables with Row Selection and Icons
- [X] Tables with Row Selection and Image Thumbnails
- [X] Tables with Icons
- [x] #526

**Comment by MaxLardenois** [comment]
OUDS : #3817
