### ISSUE TITLE
Docs > Components > Button-group > Split button : Fix split buttons design (vertical variation)

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#1116]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In their vertical variation, the design of split buttons needs the following fixes:
- [ ] **on button label part `:active`**:  the bottom border below the arrow stays black instead of turning orange. Maybe fixed with #1164.
![image](https://user-images.githubusercontent.com/89514509/159300391-08465f2e-cf5f-4270-802c-999eb4124345.png)
See design reference at https://system.design.orange.com/0c1af118d/p/0434ad-split-buttons/b/99cdab, paragraph States/Primary button.

- [ ] **on button's arrow part `:active`**: the entire border shall turn orange but instead stays black 
 ![image](https://user-images.githubusercontent.com/89514509/159302039-6dfc3dd4-c8fb-440f-9192-e66494a37374.png)

- [ ]  **on button's arrow part `clicked`**: the dropdown menu that appears is 1 px too low or too high (if it drops up).
![image](https://user-images.githubusercontent.com/89514509/159302425-2f5b3d5b-0285-45ec-afe1-4e1819bf984a.png)

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

v5.1.0

**Comment by hannahiss** [comment]
For part 2 (on button's arrow part :active: the entire border shall turn orange but instead stays black) : I see that there is already a change between published 5.1 and main branch.
See below :
![image](https://user-images.githubusercontent.com/16681352/160106578-5bd50a2a-dc28-48bd-b6d0-f4efba31e2d8.png)

**Comment by hannahiss** [comment]
**part 1 : on button label part** :active: the bottom border below the arrow stays black instead of turning orange
Seems ok on branch of PR #1164 
![image](https://user-images.githubusercontent.com/16681352/161300469-40398a04-5e79-41ec-a3c0-4bd5f0f96f8a.png)

**part 2 : on button's arrow part** :active: the entire border shall turn orange but instead stays black. On branch ofr PR #1164 you can see that the border now turns on orange which is ok. I don't know how to change border of button **BEFORE** the one active.
![image](https://user-images.githubusercontent.com/16681352/161300814-4a4c1c7c-be5e-431f-aae1-023fa023ee2b.png)

**part 3 : on button's arrow part clicked**: the dropdown menu that appears is 1 px too low or too high (if it drops up).
The positionning is done with a transform attribute, by translate. I couldn't find it in scssnor in js... 
![image](https://user-images.githubusercontent.com/16681352/161301529-2ef9d586-9475-4f69-bc99-2ae5dd560583.png)
