### ISSUE TITLE
Components with dark background for all components

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#1139]
This issue will provide a dark variant for all components in Boosted.

## List of components

- [ ] Components
  - [x] Accordion
  - [x] Alerts
  - [x] Back to top (See #1428) Not needed.
  - [x] Badge (Not in DSM and easy to change with `.bg-*` utilities)
  - [x] Breadcrumb (See #1430)
    - [x] Boosted
    - [x] ODS
    - [x] Zeplin
  - [x] Buttons - standard
    - [x] Boosted
    - [x] ODS a bit weird I guess but [here](https://system.design.orange.com/0c1af118d/p/278ebc-standard-buttons/b/247486)
    - [x] Zeplin
  - [x] Button - group (not in DSM)
  - [x] Cards (Fait avec des utilities autre que bg-dark dans Boosted)
  - [x] Carousel (navigation)
    - [x] Boosted (Almost implemented but ff7900 instead of f16e00 on white)
    - [x] ODS (actually werid pagination dots)
    - [x] Zeplin
  - [ ] Close button (See #1489)
    - [ ] Boosted Not fully implemented (missing with border example)
    - [ ] ODS Not explicit
    - [x] Zeplin
  - [x] Collapse (no spec)
  - [x] Dropdowns (not the multiple one not sure for normal dropdowns implementation colors, but at least it's consistent in #1164)
  - [ ] List group (See #1467)
  - [x] Modals no specs, but easy to implement in Boosted)
  - [x] Navs and tabs - tabs (Waiting for #1427)
    - [x] Boosted
    - [x] ODS
    - [x] Zeplin
  - [x] Navbars (no specs or Orange navbar and already fine)
  - [x] Offcanvas (no specs)
  - [x] Orange footer
  - [x] Orange navbar
  - [x] Pagination (See #1433)
    - [x] Boosted
    - [x] ODS
    - [x] Zeplin
  - [x] Placeholders (no specs and no need imo)
  - [x] Popovers (no need ?) not needed
  - [x] Progress/Spinners - progress indicators
  - [x] Scrollspy (no specs + dark variant made by other components)
  - [x] Stepped process (See #1434)
    - [x] Boosted
    - [x] ODS
    - [x] Zeplin
  - [x] Stickers (no specs and easy to change for us if needed)
  - [x] Toasts (no specs)
  - [x] Tooltips not needed
- [x] Content
  - [x] Tables (comes fully implemented with #859)

## Tasks

- [x] #1140
- [ ] #1234
