### ISSUE TITLE
CSS Variables for all components

### ISSUE THREAD

**Issue by louismaximepiton** [Orange-OpenSource/Orange-Boosted-Bootstrap#1196]
### Process

* Choose one use case in this list, please write your pseudo next to the point you take
* Create a branch and a PR for this use case
* In this list, add at the end of the corresponding line a link to the PR
* When the PR is merged, check the use case in the list

**Note**: Please try to avoid creating a PR that handles several use cases at the same time; it will be easier to track the use cases and easier for the reviewers with small PRs.

When all the checkboxes are checked, this issue can be closed.

### Proposal

We need to improve our components and our modifications to use CSS variables such as Bootstrap. However, we could trim the unused variables to reduce our package size. Here is the issue tracking what are the remaining components : 

- [x] Accordions
  - [x] Update our Boosted mods
  - [x] Trimmed for Boosted
- [x] Alerts
  - [x] Update our Boosted mods (Need to discuss a bit about it + See #1165) (See #1424)
  - [x] Trimmed for Boosted
- [x] Back-to-top (See #1258)
- [x] Badge
  - [x] Update our Boosted mods
  - [x] Trimmed for Boosted
- [x] Breadcrumb
  - [x] Update our Boosted mods (See #1252)
  - [x] Trimmed for Boosted
- [ ] _Button-group (Waiting for Bootstrap)_ -> Will probably not happen
  - [ ] Update our Boosted mods
  - [ ] Trimmed for Boosted
- [x] Buttons
  - [ ] Update our Boosted mods (See #1426)
  - [x] Trimmed for Boosted
- [x] Cards
  - [x] Update our Boosted mods (See #1253)
  - [x] Trimmed for Boosted
- [ ] _Carousel (Waiting for Bootstrap)_
  - [ ] Update our Boosted mods
  - [ ] Trimmed for Boosted
- [x] _Close-button (Waiting for Bootstrap)_ Not waiting for Bootstrap since they're based on filter
  - [x] Update our Boosted mods (See #1531)
  - [x] Trimmed for Boosted
- [x] Dropdown
  - [x] Update our Boosted mods (See #1279)
  - [x] Trimmed for Boosted (See #1423)
- [x] Footer (See #1239)
- [x] Grid
  - [x] Update our Boosted mods
  - [x] Trimmed for Boosted
- [x] List groups
  - [x] Update our Boosted mods
  - [x] Trimmed for Boosted (See #1417)
- [x] Modals
  - [x] Update our Boosted mods
  - [x] Trimmed for Boosted (See #1418)
- [x] Nav
  - [x] Update our Boosted mods (See #1427)
  - [x] Trimmed for Boosted
- [x] Navbar
  - [x] Update our Boosted mods (See #1422)
  - [x] Trimmed for Boosted
- [x] Offcanvas
  - [x] Update our Boosted mods (#1271)
  - [x] Trimmed for Boosted
- [x] Orange-navbar (See #1422)
- [x] Pagination
  - [x] Update our Boosted mods (See #1268)
  - [x] Trimmed for Boosted
- [ ] _Placeholders (Waiting for Bootstrap)_
  - [ ] Update our Boosted mods
  - [ ] Trimmed for Boosted
- [x] Popover
  - [x] Update our Boosted mods
  - [x] Trimmed for Boosted
- [x] Progress
  - [x] Update our Boosted mods (See #1254)
  - [x] Trimmed for Boosted
- [x] Spinners
  - [x] Update our Boosted mods
  - [x] Trimmed for Boosted
- [x] Stepped process (See #1281)
- [x] Sticker (via #1251)
- [x] Title bars (See #1259)
- [x] Toasts
  - [x] Update our Boosted mods
  - [x] Trimmed for Boosted
- [x] Tooltip
  - [x] Update our Boosted mods
  - [x] Trimmed for Boosted

### Motivation and context

Be closer to Bootstrap and add more flexibility to our framework.
