### ISSUE TITLE
Docs > Components > Dropdowns : Fix colors + labels + arrow direction

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#1328]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

This issue comes from the work done in Issue https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1201 List in all the doc the incompatibility with ODS in which all Boosted components (variants included) have been inspected in order to identify the ones that do not respect ODS specifications and therefore need an alert message saying "Do not use in ODS".
Doing this work, design bugs were noticed.

**Design bug to be corrected:**

- docs/v5.1/components/dropdowns:
    - **#single-button**: 
        - [x] Dropdown menu not positioned correctly => fixed in #1164
        - [X] Dropdown field color when drop-down menu shows not correct => ⚠️ fixed in #1164
        - [x] Dropdown field color for each state is to be checked and fix
            - [x] hover => ⚠️  can't be fixed because we don't have the design specifications yet
            - [x] active
            - [x] focus => ⚠️ fixed in PR #1437
        - [x] ~~Replace the dropdown field label by "Dropdown"~~  ⚠️ abandoned
        - [x] ~~If it is a better practice to use `<button>` instead of `<a>` or the opposite, add in the text the one that is more suitable to use.~~ ⚠️ abandoned :  Will be done by Bootstrap in the next version
        - [x] ~~Is the dropdown field indicated by default a place holder or a selected item ? Depending on the answer, fix the style accordingly~~ => ⚠️ Abandoned here. To be replaced by a card in the design board?

   - **#split-buttons**: 
       - [x] Fix the color border when the menu button part (part with the arrow) is pressed. ⚠️ Can't be done using css => see if design can be changed
      **Now:**
      ![image](https://user-images.githubusercontent.com/89514509/177733966-01435202-3051-4dcc-a1e5-96114529868d.png)
      **Should be:**
     ![image](https://user-images.githubusercontent.com/89514509/177735313-b1be2fd7-b64a-46be-a75d-6ea417be741f.png)

        - [x] When the dropdown menu is displayed after a click on the menu button (part with the arrow), the menu button background color is not the correct one => to be fixed    (See ODS https://system.design.orange.com/0c1af118d/p/0434ad-split-buttons/b/99cdab)    
    **Now:**
    ![image](https://user-images.githubusercontent.com/89514509/177813059-b4128355-2d4d-4d6d-b8d9-d0b4aef5eb4f.png) <br>
    **Should be:**
    ![image](https://user-images.githubusercontent.com/89514509/177813199-6e9ab035-d33c-4e1e-b90e-fe5d4952961a.png)
Fix proposed in PR #1164. ⚠️ The proposed look will need to be confirmed by the design because there is an inconsistency in ODS between the "Split buttons" component and the one in the "Standard buttons" component.

    - **#dark-dropdown**: 
        - [x] Fix the colors for all the examples. ⚠️ Fix proposed in PR #1164. Design to check once the design states specifications will be available.
            - [x] hover => ⚠️  can't be fixed because we don't have the design specifications yet
            - [x] active
            - [x] focus => ⚠️ fixed in PR #1437
    
    - **#active**: 
        - [x] Fix the colors for all the examples, including on hover state  => Fixed by #dark-dropdown
  
    - **#menu-alignment**: 
        - [x] ~~Fix the length of the dropdown menu. It should be of the length of the dropdown field, but not longer.~~ ⚠️ Abandoned to show what is possible from a technical point of view. Therefore, to be replaced by a design callout in #1199.

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

v5.1

**Comment by louismaximepiton** [comment]
Seen with Isabelle. Can be closed as-is.
