### ISSUE TITLE
[Talk] Boosted, for Orange branded and accessible websites

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/Orange-Boosted-Bootstrap#1476]
# Description
To support the Orange Dev and Test Days Conferences a talk needs to be prepared to support this subject.

# Subtasks
- [ ] articulate the content to be presented
- [ ] create the powerpoint slides
- [ ] create the script of the full presentation
- [ ] presentation rehearsals
- [x] identify the detailed location of the presentation
- [ ] test the material configuration in the destination location
- [ ] record the presentation

**Comment by hannahiss** [comment]
The conference takes place on October 6 2022, in the Armor amphitheater, from 11:30 a.m. to 12:15 p.m.
