### ISSUE TITLE
[Talk] Orange Design System for Developers

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/Orange-Boosted-Bootstrap#1480]
# Description
To support the Orange Dev and Test Days Conferences a talk needs to be prepared to support this subject.

# Subtasks
- [ ] articulate the content to be presented
- [ ] create the powerpoint slides
- [ ] create the script of the full presentation
- [ ] presentation rehearsals
- [ ] identify the detailed location of the presentation
- [ ] test the material configuration in the destination location
- [ ] record the presentation
