### ISSUE TITLE
Storybook enhancements

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#1626]
### Context

https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/565 introduced the usage of Storybook in Boosted as a link between Boosted documentation and the [Design System Manager (DSM)](https://system.design.orange.com/).
In some DSM "Develop" tabs, an iframe shows some components in action that are in fact Storybook stories from our "hidden" URL https://boosted.orange.com/storybook/.

However, the integration of Storybook within Boosted can be improved. This story is an epic one listing independent micro-tasks that should be tackled in different PRs. No need to create sub-issues.

### Enhancements

- [x] Introducing new dependencies ended up having some vulnerable dependencies in our `package-lock.json`
* `trim-newlines` that is patched in 3.0.1
* `glob-parent` that is patched in 5.1.2
* `trim` (because of `@storybook/addon-essential@6.5.13` and `@storybook/html@6.5.13`) that is patched in 0.0.3

Tackled by #2103 ?

---

- [x] Error message when running `npm run storybook-build` and then `npm run storybook`

```
...
> boosted@5.2.1 docs-vnu
> node build/vnu-jar.js

"file:/Users/ju/Orange-Boosted-Bootstrap/_site/storybook/index.html":1.38-1.60: info warning: Self-closing tag syntax in text/html documents is widely discouraged; it's unnecessary and interacts badly with other HTML features (e.g., unquoted attribute values). If you're using a tool that injects self-closing tag syntax into all void elements, without any option to prevent it from doing so, then consider switching to a different tool.
"file:/Users/ju/Orange-Boosted-Bootstrap/_site/storybook/index.html":1.87-^C
```

`vnu-jar.js` doesn't like things generated in Storybook build. `rm -rf site/storybook _site/storybook/` can help to reset the environment but a fix should be found to avoid having this error.

---

- [ ] Fix deprecation warning displayed when running `npm run storybook`

```
(node:24011) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

--- 

- [x] Bump `sass-loader` dep to the latest version

Right now if we do `npm i sass-loader@latest` and run `npm run storybook` we end up with the following error:

Tackled by #2103.

```
ERROR in ./.storybook/storybook.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./.storybook/storybook.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/Users/ju/Orange-Boosted-Bootstrap/node_modules/sass-loader/dist/index.js:27:24)
 @ ./.storybook/storybook.scss 2:26-134 53:4-74:5 56:18-126
 @ ./.storybook/preview.js
 @ ./.storybook/preview.js-generated-config-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/html/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/html/dist/esm/client/docs/config-generated-config-entry.js ./node_modules/@storybook/addon-a11y/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-docs/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/preview.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js
```

---

- [x] Bump `babel-loader` dep to the latest version

Right now, `npm run storybook` crashes after the generation of all stories.

Tackled by #2103.

---

- [x] Some addons can probably be removed safely to lighten our dev deps: `@storybook/addon-actions`, `@storybook/addon-interaction` and `@storybook/addon-links`

Tackled by #2103.

---

- [x] JS is not working within the iframe in the DSM or within the Docs page in Storybook itself

Might be tackled by #2103. See https://deploy-preview-2103--boosted.netlify.app/storybook/?path=/docs/components-tooltips--docs.

Reproducible by going to https://boosted.orange.com/storybook/?path=/docs/components-tooltips--tooltips-0 and trying to play with the tooltips. Even if the JS code is embedded in the corresponding story, JS code isn't executed.

---

- [x] Retrieve the list of components automatically in `create-stories-from-doc.js`. See https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/3dfb87cb46d3ebf51242e8dcc636e551f17e945e/stories/create-stories-from-doc.js#L41-L78.

Tackled via #2130.

---

- [x] Avoid having to duplicate the JS code to embed in the stories.

Tackled via #2130.

https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/3dfb87cb46d3ebf51242e8dcc636e551f17e945e/stories/create-stories-from-doc.js#L72-L77

We could probably use the same technic that is used for StackBlitz

---

- [x] Make all JS components work in Storybook. Currently only the tooltips are working

Tackled by #2130.

---

- [x] Go through each items in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/565#issuecomment-860634067 and create sub-tasks here to improve the rendering and manipulations of the components in Storybook. It is possibily linked to what's been done already for StackBlitz.

Tackled by #2130.

---

- [x] #2134

Tackled by #2130.
