### ISSUE TITLE
Update Boosted based on UI Kit v5

### ISSUE THREAD

**Issue by Franco-Riccitelli** [Orange-OpenSource/Orange-Boosted-Bootstrap#1761]
_FYI, the priorization is to take the `change`s and the `check`s before the `new`s_

This epic issue will track all the modifications embedded in the new UI Kit v5.0 so that Boosted can be updated.

### Placeholder `new`

- [ ] Dark variant has been added

### Close button `change`

- [x] [Close button now has a mandatory tooltip](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1773)

### Focus state `check`

Focus state added to components and modules. It's already been tackled by https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1437 so the only action identified here would be to double-check that we haven't forgotten anything.

- [x] #1785

### File input `change`

- [x] #1780

### Story button `new`

- [ ] Story button component added to Navigation category. (See prototype in #1816)

### Toggle switch `check`

- [x] Updated Toggle switch variant with On/Off label. See #1796.

### Colour picker `change`

- [x] [Colour picker component customised from Boosted library, added to Forms.](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1794)

### Date picker `new`

- [ ] Updated Date picker with month and year dropdown options.

### List group `change`

- [x] #1467

### Accordion `change`

- [x] #1791 

### Dropdown `new`

- [ ] Updated dropdown list single selection with search filter in dropdown field.

### Split button `check`

- [x] Split button arrow orientation options added. Customised from Boosted library. See #1793.

### Data tables `new`

- [x] #1781

### Title bar `new`

- [ ] 50px title size option added to Title bars for Large desktop and Medium desktop breakpoint sizes (note: the baseline remains the same)

### Slider `new`

- [ ] Updated slider control with tooltip displaying values.

### Pagination dots `change`

- [x] Play/Pause optional control added to Pagination dots. #1763

### Tags `check`

- [x] Dual selection interaction removed from Tag component. See #1795.

### Back to top button `check`

- [x] Updated Back to top button variant with a label added.

### Alerts `change` **_:warning: On hold since need of an icon_**

- [ ] Updated Alerts with new functional colours for use on white and black backgrounds.
- [x] Updated Warning icon.
- [ ] The 4 icons must be updated everywhere in the framework and should use a solid color in the center (not transparent) otherwise it won't work with all background colors

### Dropdown list arrow `change`

- [ ] [Updated Dropdown list arrow orientation points up when in the open state and down in the closed state.](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1628)

### Social buttons `new`

- [x] [TikTok social button added.](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1766)

### Help text `change`

- [x] [Help text added as a variant to Text Fields.](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1767)

### Tabs dropdown `new`

- [x] Standard Tabs and Tabs light now include a dropdown variant as the last entry in a tab group. #2007.

### Tooltips & popovers `change`

- [x] New design: [Update tooltips and popover design according to UI Kit v5 #1803](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1803)

**Comment by hannahiss** [comment]
File input field is OK as it is currently in Boosted. After design review, and technical impossibility to realize fully the design that was wanted, Franco agreed to change it slightly to match the current design => no change is needed anymore in code

**Comment by MaxLardenois** [comment]
Boosted, won't fix
