### ISSUE TITLE
[Tracking] Color mode

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#1776]
This issue will track tasks identified around the current development of color mode in Boosted.
It follows up https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1757.

⚠️ For the v5.3 we need not to forget to revert https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1841

If v5.3.0 must be released without the dark mode some tasks must be tackled:
* ~~`$enable-dark-mode` should be `false` by default in Boosted. The documentation should reflect this choice and the `dist/*` files shouldn't embed any of things related to the dark mode?~~

- [ ] https://main--boosted.netlify.app/docs/customize/color-modes/
  - Complete review and rewrite depending if we have or not the dark mode or only the color mode as optional
  - Would need to replace Bootstrap by Boosted in most cases  
- [ ] https://main--boosted.netlify.app/docs/customize/colors/
  - Complete review and rewrite depending if we have or not the dark mode or only the color mode as optional
  - Need to check how to modify the content to be compatible with Boosted without losing Bootstrap info
- [ ] https://main--boosted.netlify.app/docs/customize/sass/ (especially if we don't have the dark mode in v5.3 because `_variables-dark.scss` would become useless and disturbing for the end-users)
  - Complete review and rewrite depending if we have or not the dark mode or only the color mode as optional  
  - Check how we can make understand the Orange developers that _variables-dark.scss is not necessary for now. But does it matter? If the bundle size doesn’t change, that’s not really an issue isn’t it? 
- [ ] https://main--boosted.netlify.app/docs/migration
  - Complete review and rewrite depending if we have or not the dark mode or only the color mode as optional
- [ ] During https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1757, most of the `$gray-500` values have been let as is in Boosted. But could `$gray-500` be defined by `--bs-tertiary-bg`? By another custom property? At least, if no existing custom property does the job, we should probably create custom properties for disabled color/bg.
- [ ] Work among all examples where we have `.bg-tertiary` + border to have more consistency. A part could be done directly in Bootstrap before.
- [ ] https://main--boosted.netlify.app/docs/utilities/background/
  - Check with the designers if `.bg-body-secondary` and `.bg-body-tertiary` are allowed. Otherwise either change their color or don't display them and mention them in the callout
- [ ] https://main--boosted.netlify.app/docs/utilities/colors/
  - Check if `.text-body-emphasis`, `.text-body-secondary` and `.text-body-tertiary` are compliant with ODS. Otherwise, we need no to display them in the list
  - Normally, `.text-muted` should have the same color as `.text-secondary`. Let's see with other commits after.
- [ ] If dark mode is not developed entirely in Boosted v5.3.0, we need to adapt the documentation
  - Make optional the display of the theme switcher (could be visible only in development), the load of `color-modes.js` and `data-bs-theme="auto"` in the HTML file. We could add a `{{ if eq. Layout "docs" }}` like to display or not the selector. Same thing for the script in `site/layouts/partials/docs-versions.html` + `$enable-dark-mode: true` + npm specific command option?
- [ ] Check the HTML structure of the dropdowns in our doc header. We probably should use `<button>`s (like in Bootstrap) rather than `<a>`s
- [ ] https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1757#discussion_r1064817150
- [ ] https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1757#discussion_r1065608172
- [ ] https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1757#discussion_r1065616382
- [ ] https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1757#discussion_r1065662815
- [ ] When the right commit will be added to Boosted from Bootstrap, don't forget to remove this modification: https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/a624a5d73f0e2c580a3daeea3f61e7d3c9e07978
- [ ] https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1757#discussion_r1066045049
- [ ] https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1757#discussion_r1066878129
- [ ] https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1828#discussion_r1102616361
- [ ] Based on https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1858/commits/591733f12ec1629302c79bae85a095e3395f537d#r1141766812, we should have some `--bs-body-color-inverted` instead of using a "background" color like `--bs-body-bg`! (Reverse to Bootstrap?)

**Comment by MewenLeHo** [comment]
Issue spotted with select element: the arrow indicator is not visible on dark theme (still here but it's black on black)

![darkselect](https://user-images.githubusercontent.com/92363071/227963854-df32fb89-85de-4ce6-a202-112ccee50b33.png)
