### ISSUE TITLE
Re-synchronize typography values with UI Kit v6

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#2504]
### Description

The aim of this issue is to re-synchronize our typography values and utilities based on the new one defined in the UI Kit v6.

For example, our `.display-1` is set to `60px` on the desktop and should be `50px`.

![Screenshot 2024-03-08 at 12 09 07](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/assets/17381666/64c35f66-1d16-49fc-b169-afe24dc5a3ae)
![Screenshot 2024-03-08 at 12 09 17](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/assets/17381666/10e6da75-3a25-4e44-ac2c-f23ec4eab252)
![Screenshot 2024-03-08 at 12 09 26](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/assets/17381666/a61394ed-eba7-44ba-98a6-c98d6e6b8097)

### Sub-tasks

- [x] Double-check that the screenshots are consistent with https://system.design.orange.com/0c1af118d/p/68dbd8-typography/b/27d9ab
- [ ] Apply correctly the new values to our typography system
- [ ] For each typography utility, check in our documentation and examples that it's still correct. I'm thinking for example of the heading of https://boosted.orange.com/docs/5.3/examples/form/ that should be `50px` instead of `60px` as newly defined in https://system.design.orange.com/0c1af118d/p/20500e-form/b/16bb53/i/108261203
- [ ] Double-check in our components and modules too if it doesn't have any impacts, components such as Title Bars for instance
- [ ] Add a migration note that summarizes the impact for the users if any
