### ISSUE TITLE
[OUDS] [Tracking] Documentation content

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#2611]
⚠️ WIP: will need to be updated after https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2612

---

### Description

The content of the OUDS Web documentation has been cleaned up. However, given that we want iso-functional versions with Boosted/Bootstrap v5.3.3, it is essential to track what was previously included in both documentation libraries to determine whether any of this information should be reintegrated.

- [ ] Header (Boosted / Bootstrap)
  - [ ] Versioning dropdown (Boosted / ~Bootstrap~) 
  - [ ] Solaris icons entry (Boosted / ~Bootstrap~)
- [ ] Footer (Boosted / Bootstrap)
- [ ] Homepage
  - [ ] Jumbotron (Boosted / Bootstrap)
  - [ ] Get started any way you want (Boosted / Bootstrap)
  - [ ] Read our getting started guides (Boosted / Bootstrap)
  - [ ] Customize everything with Sass (Boosted / Bootstrap)
  - [ ] Build and extend in real-time with CSS variables (Boosted / Bootstrap)
  - [ ] Components, meet the Utility API (Boosted / Bootstrap)
  - [ ] Powerful JavaScript plugins without jQuery (Boosted / Bootstrap)
  - [ ] Orange Design System for web (Boosted / ~Bootstrap~)
- [ ] Dark mode page (Boosted / ~Bootstrap~)
- [ ] All versions (Boosted / Bootstrap)
- [ ] Design guidelines (Boosted / ~Bootstrap~)

---

```
WARN  Template _default/_markup/render-image.html is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/_default/_markup/render-image.html
WARN  Template partials/callouts/danger-async-methods.md is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/partials/callouts/danger-async-methods.md
WARN  Template partials/callouts/info-mediaqueries-breakpoints.md is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/partials/callouts/info-mediaqueries-breakpoints.md
WARN  Template partials/callouts/info-npm-starter.md is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/partials/callouts/info-npm-starter.md
WARN  Template partials/callouts/info-prefersreducedmotion.md is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/partials/callouts/info-prefersreducedmotion.md
WARN  Template partials/callouts/info-sanitizer.md is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/partials/callouts/info-sanitizer.md
WARN  Template partials/callouts/warning-color-assistive-technologies.md is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/partials/callouts/warning-color-assistive-technologies.md
WARN  Template partials/callouts/warning-data-bs-title-vs-title.md is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/partials/callouts/warning-data-bs-title-vs-title.md
WARN  Template partials/callouts/warning-input-support.md is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/partials/callouts/warning-input-support.md
WARN  Template partials/guide-footer.md is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/partials/guide-footer.md
WARN  Template partials/js-data-attributes.md is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/partials/js-data-attributes.md
WARN  Template partials/responsive-img.html is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/partials/responsive-img.html
WARN  Template partials/table-content.html is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/partials/table-content.html
WARN  Template shortcodes/added-in.html is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/shortcodes/added-in.html
WARN  Template shortcodes/bs-table.html is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/shortcodes/bs-table.html
WARN  Template shortcodes/callout-deprecated-dark-variants.html is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/shortcodes/callout-deprecated-dark-variants.html
WARN  Template shortcodes/deprecated-in.html is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/shortcodes/deprecated-in.html
WARN  Template shortcodes/design-callout-alert.html is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/shortcodes/design-callout-alert.html
WARN  Template shortcodes/docsref.html is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/shortcodes/docsref.html
WARN  Template shortcodes/enable-btn-close-tooltip.html is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/shortcodes/enable-btn-close-tooltip.html
WARN  Template shortcodes/js-dismiss.html is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/shortcodes/js-dismiss.html
WARN  Template shortcodes/markdown.html is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/shortcodes/markdown.html
WARN  Template shortcodes/partial.html is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/shortcodes/partial.html
WARN  Template shortcodes/placeholder.html is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/shortcodes/placeholder.html
WARN  Template shortcodes/svg-docs.html is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/shortcodes/svg-docs.html
WARN  Template shortcodes/table.html is unused, source file /Users/ju/Orange-Boosted-Bootstrap/site/layouts/shortcodes/table.html
```

**Comment by julien-deramond** [comment]
Closing this one. Will be handled in #2589.
