### ISSUE TITLE
Clean branch as a starting point for v5

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#283]
## To update

- [x] Bootstrap name
- [x] Logos
- [x] README, credits⋅
- [x] repo URL, project name, etc.
- [x] Tools config files
- [x] source files
- [x] dist files
- [x] Netlify conf

### Content to modify

- [x] assets: logo, favicon…
- [x] Bootstrap → Boosted
- [x] Homepage
- [x] About / Team
- [x] About / Brand
- [x] About / Licence
- [x] About / Cookies

### Content to add

- [x] About / Boosted history?
- [x] Tarteaucitron + About / Cookies
 
## To remove

Mainly to match Orange Brand Digital Guidelines:

- [x] List groups, with checkboxes: remove example without labels
- [x] Forms: remove "Without labels" examples (eg in "Checks")? 
- [x] btn-outline
- [x] table bordered / borderless
- [x] zebra tables
- [x] table backgrounds
- [x] thead background's variants
- [x] pagination sizing
- [x] text-justify, text-uppercase
- [x] font-weight except 400 + 700
- [x] border-radius (in border utility page)
- [x] box-shadow utility page
- [x] "Themes", "Expo" and "Blog" links…
- [x] useless SVG in assets 5BS logos, etc.)
- [x] remove unusded styles in docs
- [ ] RFS: fluid values will not please Orange Brand, so it's a No Go I guess (pending request)

## To question

- [x] ~~"Examples" template section~~

## To propose via PR

- [x] add `aria-current` on navbars (including scrollspy and documentation itself) … [#30079 in Bs](https://github.com/twbs/bootstrap/pull/30079)
- [x] Spinners: if `prefers-reduced-motion`, display text and disable animation [#30081 in BS](https://github.com/twbs/bootstrap/pull/30081)
- [x] SVG placeholders: add `focusable="false"` for IE11 → [#30075 in BS](https://github.com/twbs/bootstrap/pull/30075)
- [x] add `role="search"` on search form in  `/site/layouts/partials/docs-subnav.html` → [#30067 in BS](https://github.com/twbs/bootstrap/pull/30067)
- [x] Slip-link to search form + TOC, when available → [#30073 in BS](https://github.com/twbs/bootstrap/pull/30073)
- [x] fix headings hierarchy, at least in About / Licence,  ([#300090 in BS](https://github.com/twbs/bootstrap/pull/30080)) and check for callout shortcode to use a custom heading level as argument…
- [x] remove redundant `role="main"` on `<main>` tags → [#30067 in BS](https://github.com/twbs/bootstrap/pull/30067)
- [x] add missing `role="contentinfo"` on `<footer>` tags → [#30067 in BS](https://github.com/twbs/bootstrap/pull/30067)
- [x] Remove `.booticons-list` in `docs.scss` → [#30071 in BS](https://github.com/twbs/bootstrap/pull/30071)

Anything else?
