### ISSUE TITLE
Port custom component

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#290]
## To implement

Except if Bootstrap v5 added equivalents components to customize (if so, try to customize Bootstrap's ones first — and in case of improvements, backport them to BS).

- [x] ~~fluid-margins full-width containers~~. **Dropped in v5**
- [x] ~~`focus-visible` polyfill and styles~~: #139 moved to 5.0.0-alpha milestone
- [x] link with arrow (#520)
- [x] Buttons: (#521)
   - [x] inversed buttons: should use custom properties to switch colors depending on context
   - [x] icons buttons: **close button should inherit those in any way— as well as pagination with icons only, isn't it?**
   - [x] social buttons
- [xm] ~~accordion: multiple openable~~ **Dropped**
- [x] megamenu: should totaly refactor this, starting by defining behaviours — and should also handle `aria-current`, I guess (#522)
- [x] ~~footer: still required as a component~~ **Example** firtst, see #410
- [x] Navbar: (#525)
  - [x] icons in navbar
  - [x] minimizing behaviour on scroll
  - [x] local + priority navigation: shouldn't this be a single component, since priority nav is based on local nav? Moreover, local nav is basically a navbar with borders…
  - [x] supra nav: mostly a navbar variant, isn't it?
  - [x] ~~nav-tabs-light~~ → done in #362, using a custom property `--bs-tabs-spacing` to reduce code overrides
- [x] Scroll up (#523)
- [x] Stepbar: also ensure to have a look at [bs-stepper](https://github.com/Johann-S/bs-stepper)
- [x] Tables: (#526)
  - [x] responsive tables (#222) 
  - [x] sortable tables (#526)
    - https://dequeuniversity.com/library/aria/table-sortable
  - [x] ~~icons in tables~~
  - [x] row selection ~~ **Example** only (#410)
- [x] Carousels: see #366 (Bootstrap-side)
- [x] tabs: maybe try to update Bootstrap's ones to comply with Heydon Pickering [Inclusive tabbed Interface Component](https://inclusive-components.design/tabbed-interfaces/)? see #140 #150 #456  

## To enhance

- [x] Colors: enforce contrasts by coupling `color` with `background-color` in utilities
- [x] color-yiq to use WCAG contrast algorithm? See #292 
- [x] background utilities using supporting colors instead of functionnal ones

## To question

Those Boosted v4 components duplicates existing Bootstrap components, so I'd recommend to try to customize Bootstrap's ones before porting those to v5.

- [x] ~~Orange popin: what's differing from Bootstrap modal?~~ → almost nothing since responsive content is achievable using grid, utilities and components…
- [x] ~~Custom carousel: shouldn't we simply override Bootstrap one?~~ → confirmed, check #366 
- [x] Orange navbar: only a navbar example with content… I guess only supra nav should remain
- [x] 3-way toggles: duplicated by "Buttons" → "Toggle states"
- [x] O-tabs: tabs component (in Bootstrap's nav) seems to do the job (see #140 #150)

**Comment by ffoodd** [comment]
Closing this after triage: either dedicated issues exist or feature/component will be dropped in v5.
