### ISSUE TITLE
New examples

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#410]
An issue to list examples requested by projects or directly by Orange brand.

## To-do list

Kind of table of contents, details below the list.

- [ ] Maps - see https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/640
- [x] Footers - see https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/922
- [x] Title Bar - see https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/956
- [x] Global Headers
- [ ] Collapsible table rows
- [ ] Table row selection
- [ ] Sticky table row / header
- [ ] Condensed UI
- [ ] Mail
- [ ] a11y guidelines
- [ ] v4 custom examples?
- [ ] Jumbotron
- [ ] Features
- [ ] Sidebars / sidenav
- [ ] Dropdowns
- [ ] List group
- [ ] Modals
- [ ] Starter template
- [x] Navbars (Go with headers ?)
- [x] RTL section

## Collapsible table rows

It requires a few tricks to handle this—however I already have [a CodePen example](https://codepen.io/ffoodd/pen/LYGpVYK), but please notice that the table structure might change depending on the relationship between collapsible rows and their trigger.

For example if the trigger lives as a global colgroup header, [it should be implemented this way](https://codepen.io/ffoodd/pen/eYJpJKV).

## a11y guidelines (#243)

Orange recommendations website uses static templates based on Boosted to ease contributions and reuse. I think it should be included in Boosted examples too, and maintained from here.

## Condensed UI (#431)

In complex applications, handling large tables and datasets, a more condensed UI would be appreciated (and has been requested).

I think we should at least try to implement a new example using small variants for components, and reducing spacings as much as possible.

## Table row selection

Since this feature is not reeally a feature right now (nothing happens beside changing the row's background) this should be implemented as an example—and not documented in the Content / Tables page.

## Sticky row / column

Pretty easy to do with CSS, I [already made a CodePen](https://codepen.io/ffoodd/pen/VwezwgQ)
Could be made as a Bootstrap table variant, see [Bootstrap #31458](https://github.com/twbs/bootstrap/issues/31458).

## Footers

Should not be a component, but definetly needs to be documented as examples (and in the Disgn Guidelines, obviously).

## Title Bar (#889)

As designed in the Web UI Kit, Title bar should be documented and shown in some examples.

## Global Headers (#525)

Following [v4 Essentials page for Global Headers](https://boosted.orange.com/docs/4.5/essentials/global-headers/), they should be documented in the Design Guidelines and shown in some examples.

## Maps

Using Leaflet:
- as done in *ocom-leaflet-static* (currently in OAB's Gitlab)
- with some [IOT-Map-Component](https://github.com/Orange-OpenSource/IOT-Map-Component) examples;
- thinking about maps accessibility ([read Benjy Stanton's post "A plan for accessible maps"](https://www.benjystanton.co.uk/blog/a-plan-for-accessible-maps/))

## Mail (?)

Email templates aren't that easy, and probably quite used at Orange. Could be valuable to make some, but that's a whole new trade.

## Blog content with & without Helvetica Now

To try variable font in the wild.

## v4 examples to bring back?

Are they needed? Could they be improved?

## Jumbotron

Equivalent of Jumbotron [example in Boosted v4](https://boosted.orange.com/docs/4.6/examples/jumbotron/). Using utilities like in [Bootstrap v5](https://getbootstrap.com/docs/5.1/examples/jumbotron/) ?

## Sidebars

Actual [sidebars example](https://boosted.orange.com/docs/5.1/examples/sidebars) looks nearly branded, but it needs some deletions and some work to follow [design guidelines](https://system.design.orange.com/0c1af118d/p/43dd8c-side-navigation/b/81ac60).

## Dropdowns

Maybe keep the [actual template](https://boosted.orange.com/docs/5.1/examples/dropdowns/) with few more examples, but dropdowns need to be reworked to follow [the brand](https://system.design.orange.com/0c1af118d/p/88ab5b-forms/b/599459) or [this](https://system.design.orange.com/0c1af118d/p/04ae65-buttons/b/48012d) ?

## List group

See with design if we keep them or not.

## Modals

Need to be reworked to be branded.

## Starter template

Do we keep it [as is](https://boosted.orange.com/docs/5.1/examples/starter-template/) or maybe as bootstrap with a starter project, or do we keep the same [example as Boosted v4](https://boosted.orange.com/docs/4.6/examples/starter-template/) ?

## Navbars

~~Need a rework on some examples presented in the actual example.~~ Should go with Headers ?

## RTL

Need to fulfill some of the examples below in rtl direction, see the [Bootstrap RTL examples](https://getbootstrap.com/docs/5.1/examples/#rtl).
