### ISSUE TITLE
ODS > Global Headers (Navbars)

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#525]
## Requirement

**For** a Developer 
**Who** is creating an Orange Website
**The** Header Integration
**is an** automated component
**that** proposes the web site's Orange Headers
**unlike** the default bootstrap framework
**Boosted** will provide this ready to use component compatible with the Orange Design and the accessibility requirements

### General Integration context
The Orange page Header is divided into 3 parts that are stacked on top of each other:
* The Supra Bar (Optional): a bar above all others that allows to select from global website context (Personal or Business / language selection) - it can also contain site action icons 
* The Global Header Bar (Mandatory): a bar that must contain the Orange or OBS Logo - it can also contain the site Title,  the Sites navigation menu, the site icons or the Search Input.
* The Stand Alone Navigation Bar (Optional): this bar only shows the navigation items

The integrating team will decide how to customize the header using these various elements to best organize the site.

The header is always sticky, i.e. it must always be displayed.

#### Supra bar menu items
* The menu items will be on a single line and will be pulled to the left of the bar and/or pulled to the right of the bar
* The menu items should reference a full site context change and should not generate sub menu items 
* The language selection can be placed in the Supra bar, in that case it should be placed on the right hand side of the bar

#### Header Action Icons
* The action icons are placed on the far right of the bar
* The action icons can include User Profile, Purchasing Cart, Search,...
* When resizing the screen the action icons should always be visible

#### Logo
* The Orange logo (aka **Master Logo**)
  * it should always be sized 50px 
  * it should never be resized
  * when the corresponding breakpoint is reached it should be switched to the small logo sized at 30px that should not be resized
* The OBS logo
  * Is the The OBS logo"Business Services" Text on 2 separate lines
  * it should stay at 50px height until the corresponding break point is reached
  * it should then stay at 30px height for the rest of the resizing
  * the OBS logo is always presented the same and should not adapt to Right to Left text positioning
* Other Logos are not taken into account in Boosted (Orange Bank, Parnasss, ...)

#### Title
* The title is left align next to the logo - Xpx margin between the two
* The Title can be set to be on 1 line or 2 lines
* The font size is 
  * 1 line: 35px
  * 2 lines: 29px
* On Resize of the screen:
  * The Title should keep the same size
  * When the text does not fit anymore the title should be removed
  * 

#### Menu items
* The menu items are listed
  * in the Global Header Bar:
     * For Orange:  left aligned to the logo or title
     * For OBS: right aligned next to the Action Icons
  * in the Stand Alone Navigation Bar: they are always left aligned and aligned to the left of the logo

#### Search Input
* it can be used in the Global header already available
* it is right aligned on the Global Header Bar
* **_??? is this true:_** When used it should not be used with the Action Icons

## Animations & Interactions
* Page Scroll
  * Header always on (Mandatory)
    * The Header is always present at the top of the viewport even when scrolling
  * Header Minimizing (Optional)
    * When the page is loaded and on first appearance, the Orange Header should be displayed in full size
    * When the user scrolls down the page the header can switch to the minimized version of the header
    * The animation between the full size and the minimized version is done XXX
* Search Action Icon
  * When the user clicks on the Search icon the Global Search bar is displayed under the Global Header bar
  * the new content is animated XXX
* Menu Item Click 
  * When the user clicks on a navigation item the Sub Navigation bar is displayed under the Global Header bar
  *  the new content is animated XXX
* Supra Bar Resizing
  * When the user resizes the screen the Supra Bar will disappear for between the screen Medium to Small
  * When the Supra Bar disappears, its content will be positioned in the Hamburger Menu
* Global Header 
  * Resizing (Optional)
    * When the user resizes the screen the Global Header will automatically adjust its content
    * First when the menu items cannot be fully displayed it disappears (as a first implementation the text will be cut and added "..." until the next break point - then a complementary implementation will correct this)
   * When the menu items disappears it's content will be positioned in the Hamburger Menu
  * Then if the Title cannot be fully displayed it disappears
  * If Action Icons are used they should always show in the header until the XS breakpoint
* Burger menu
  * When the user clicks on the burger menu icon, the menu opens
  * The burger menu will always display all these items in the following order : 
    * Supra bar left menu items
    * GH nav-links
    * SB right menu items
    * Action icons
    * Stand alone nav-links

### Visual Accessibility
All navigational items inside the Header have been designed to be accessible

### Usage Accessibility
all navigational items inside the Header need to be accessible through
* a keyboard
* or a screen reader

When you are on the home page of your site the order with which to navigate in the header is:
* Logo
* Header Title
* Supra bar left items
* Supra bar right items
* Site navigation items
* Action icons

When you are on a secondary page of the site the user should skip to main content directly

When an item is selected it needs to be described as selected to understand the selection status

## Architecture & Technical Implementation
// To be clarifed if still needed
- [x] Drop color schemes
- [x] Icons in navbar (button icon as in #521?)
- [x] minimize on scroll
  - [x] ensure `sscroll-padding-top` evolves accordingly (see #622)
- [x] supra bar: mostly a navbar variant, isn't it?
  - Should the hiding behaviour when minimizing stay in v5?
  - Would it simply be part of the minimizing behaviour?
- [x] ~~priority / local navigation: shouldn't this be a single component, since priority nav is based on local nav? Moreover, local nav is basically a navbar with borders…~~ Local Headers made their way to #537 since they need a specific behaviour.

## References

- **Orange Design System**: [Modules > Global Headers](https://system.design.orange.com/0c1af118d/p/37609b-global-headers/b/366c91) and [Modules > Global Search](https://system.design.orange.com/0c1af118d/p/42765f-global-search/b/2696bb) and [Modules > Global Menu](https://system.design.orange.com/0c1af118d/p/84c686-global-menu/b/98bda0)
- **v4**: https://boosted.orange.com/docs/4.5/components/navbar-orange/

## Components

- [x] #699
- [x] #700
- [x] #701
- [x] #702 
- [x] #703 
- [x] #704 
- [x] #705
- [x] #706
- [x] #707
- [x] #709
- [x] #710

**Comment by julien-deramond** [comment]
## Prioritized for the Sprint 1

- [ ] Supra bar (WEB-GLH-SUB-001): Global header Supra bar standard
- [ ] Supra bar (WEB-GLH-SUB-002): Global header Supra Bar with language options
- [ ] Supra bar (WEB-GLH-SUB-003): Global header Supra Bar with icons + Supra bar with icons authenticated
- [ ] Global Header (WEB-GLH-STN-001): Global header standard with search, shopping basket and avatar icons
- [ ] Global Header (WEB-GLH-MIN-001): Global header miniminised with search, shopping basket and avatar icons
- [ ] Global Header (WEB-GLH-TNI-001): Global header with title, navigation and icons
- [ ] Global Header (WEB-GLH-TNI-002): Global header on 2 lines with search, shopping basket and avatar icons
- [ ] Global Header (WEB-GLH-TNI-003): Global header with title and navigation bar
- [ ] Global Header (WEB-GLH-TNI-004): Global header with title on 2 lines and navigation bar
- [ ] Global Header (WEB-GLH-NSC-001): Global header standard with search box
- [ ] Global Header (WEB-GLH-OBS-001): Global header standard
- [ ] Global Header (WEB-GLH-OBS-002): Global header standard with navigation bar
